---
title: "Project A Examples"
author: "Thomas E. Love, Ph.D."
date-modified: last-modified
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

# Project A Plan Materials

1. The **Project A Plan template**, is available as part of [the 431-data site](https://github.com/THOMASELOVE/431-data). It is called `431-projectA-plan-template.qmd`. 
    - An [HTML version is also available to view at RPubs](https://rpubs.com/TELOVE/ProjectA-plan-template-431-2024).
    
2. A [sample Project A Plan](https://rpubs.com/TELOVE/ProjectA-sample-plan-431-2024), built by Dr. Love to help people who need to make revisions to their Plan after the initial version [is available now](https://rpubs.com/TELOVE/ProjectA-sample-plan-431-2024). 

3. A list of the [17 elements we will review](https://github.com/THOMASELOVE/431-classes-2024/blob/main/projectA/plan_checklist.md) closely in deciding whether or not to accept your Project A Plan [is provided here](https://github.com/THOMASELOVE/431-classes-2024/blob/main/projectA/plan_checklist.md).

# Project A Portfolio Report Materials

3. The **Project A Portfolio Report template** is also available as part of [the 431-data site](https://github.com/THOMASELOVE/431-data). It is called `431-projectA-portfolio-report-template.qmd`. 
    - An [HTML version is also available to view at RPubs](https://rpubs.com/TELOVE/ProjectA-portfolio-report-template-431-2024).

:::{.callout-note}

The Template for the Portfolio Report is identical to the Template for the Project A Plan except that it:

- deletes the old section 13, and 
- adds in headings for the new sections 13-16, while 
- moving the session information from section 14 to section 17.

:::